2021/01/14 12:00:32 : orders_errors 1: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1289, in convert_order_export
    # order_status_history = get_list_from_list_by_field(orders_ext['data']['orders_status_history'], 'orders_id', order['orders_id'])
KeyError: 'orders_status_history'

2021/01/14 12:00:35 : orders_errors 2: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1289, in convert_order_export
    # order_status_history = get_list_from_list_by_field(orders_ext['data']['orders_status_history'], 'orders_id', order['orders_id'])
KeyError: 'orders_status_history'

2021/01/14 12:00:35 : orders_errors 3: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1289, in convert_order_export
    # order_status_history = get_list_from_list_by_field(orders_ext['data']['orders_status_history'], 'orders_id', order['orders_id'])
KeyError: 'orders_status_history'

2021/01/14 12:00:35 : orders_errors 4: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1289, in convert_order_export
    # order_status_history = get_list_from_list_by_field(orders_ext['data']['orders_status_history'], 'orders_id', order['orders_id'])
KeyError: 'orders_status_history'

2021/01/14 12:00:54 : orders_errors 5: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1289, in convert_order_export
    # order_status_history = get_list_from_list_by_field(orders_ext['data']['orders_status_history'], 'orders_id', order['orders_id'])
KeyError: 'orders_status_history'

2021/01/14 12:00:54 : orders_errors 6: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1289, in convert_order_export
    # order_status_history = get_list_from_list_by_field(orders_ext['data']['orders_status_history'], 'orders_id', order['orders_id'])
KeyError: 'orders_status_history'

2021/01/14 12:00:54 : orders_errors 7: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1289, in convert_order_export
    # order_status_history = get_list_from_list_by_field(orders_ext['data']['orders_status_history'], 'orders_id', order['orders_id'])
KeyError: 'orders_status_history'

2021/01/14 12:00:54 : orders_errors 8: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1289, in convert_order_export
    # order_status_history = get_list_from_list_by_field(orders_ext['data']['orders_status_history'], 'orders_id', order['orders_id'])
KeyError: 'orders_status_history'

